### ISSUE TITLE
Terrestrial or Satellite AIS?

### ISSUE THREAD

**Issue by jlgabbar** [aisstream/issues#1]
Hi,

I've been looking for something like this for a while. Is this using terrestrial or satellite AIS? I would assume terrestrial but was just curious. Would love to even find a way to contribute.

**Comment by aisstream** [comment]
Hello, 

Due to cost and licensing constraints associated with giving data away for free this is unfortunately only terrestrial AIS. The affects of this is visible in our reduced coverage in Africa and South America. 

Thank you for your offer to contribute! For the time being aisstream.io will remain close source but we will definitely each out if that changes. Thanks for giving us a try!

**Comment by cargosoft2** [comment]
Hi 
we are try now to connect to ais 10.1.2023.16:50 German Time, but we are not receiving any data. Is there any Problem in the service?
thanks

**Comment by aisstream** [comment]
Hi @cargosoft2 could you create a new issue with the problem you were experiencing. I will investigate our logs to see if there were any availability issues at this time.

**Comment by cargosoft2** [comment]
> Hi @cargosoft2 could you create a new issue with the problem you were experiencing. I will investigate our logs to see if there were any availability issues at this time.
Hi , we resolved the problem on our side. thks

**Comment by aisstream** [comment]
@cargosoft2 thank you for the update.
